/*
 *  aescrypt.idl
 *
 *  Copyright (C) 2024
 *  Terrapane Corporation
 *  All Rights Reserved
 *
 *  Author:
 *      Paul E. Jones <paulej@packetizer.com>
 *
 *  Description:
 *      IDL source for AES Crypt the defines the shell extension interface.
 *
 *  Portability Issues:
 *      None.
 */

// This file will be processed by the MIDL tool to
// produce the type library (aescrypt.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
    object,
    uuid(3E228AAF-683B-44AD-A8DA-3FC8EF25008A),
    helpstring("IAECryptShellExtension Interface"),
    pointer_default(unique)
]
interface IAESCryptShellExtension : IUnknown{
};
[
    uuid(EB9FFF86-F4EC-4882-B45E-90C4EB1ECC07),
    version(4.0),
    helpstring("AES Crypt Type Library")
]
library AESCryptLib
{
    importlib("stdole2.tlb");
    [
        uuid(35872D53-3BD4-45FA-8DB5-FFC47D4235E7),
        helpstring("AESCryptShellExtensionCom Class")
    ]
    coclass AESCryptShellExtensionCom
    {
        [default] interface IAESCryptShellExtension;
    };
};
